# Generated by Django 3.1.4 on 2021-01-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vertical_farm_2',
            fields=[
                ('idVf2', models.AutoField(db_column='idVf2', primary_key=True, serialize=False)),
                ('Available_capacity', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
