# Generated by Django 3.1.4 on 2021-02-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='produce_orders',
            fields=[
                ('idOrder', models.AutoField(db_column='idOrder', primary_key=True, serialize=False)),
                ('Produce_type', models.CharField(max_length=50)),
                ('Qty', models.IntegerField(blank=True, null=True)),
				('Vf_Order', models.CharField(max_length=50)),
            ],
        ),
    ]
