# Generated by Django 3.1.4 on 2021-03-23 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_produce_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='vertical_farm_1',
            fields=[
                ('idVf1', models.AutoField(db_column='idVf1', primary_key=True, serialize=False)),
                ('Available_capacity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vertical_farm_10',
            fields=[
                ('idVf10', models.AutoField(db_column='idVf10', primary_key=True, serialize=False)),
                ('Available_capacity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vertical_farm_3',
            fields=[
                ('idVf3', models.AutoField(db_column='idVf3', primary_key=True, serialize=False)),
                ('Available_capacity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vertical_farm_4',
            fields=[
                ('idVf4', models.AutoField(db_column='idVf4', primary_key=True, serialize=False)),
                ('Available_capacity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vertical_farm_5',
            fields=[
                ('idVf5', models.AutoField(db_column='idVf5', primary_key=True, serialize=False)),
                ('Available_capacity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vertical_farm_6',
            fields=[
                ('idVf6', models.AutoField(db_column='idVf6', primary_key=True, serialize=False)),
                ('Available_capacity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vertical_farm_7',
            fields=[
                ('idVf7', models.AutoField(db_column='idVf7', primary_key=True, serialize=False)),
                ('Available_capacity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vertical_farm_8',
            fields=[
                ('idVf8', models.AutoField(db_column='idVf8', primary_key=True, serialize=False)),
                ('Available_capacity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vertical_farm_9',
            fields=[
                ('idVf9', models.AutoField(db_column='idVf9', primary_key=True, serialize=False)),
                ('Available_capacity', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
