# Generated by Django 3.1.4 on 2021-04-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_produce_orders_vf_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce_orders',
            name='Produce_type',
            field=models.CharField(max_length=45),
        ),
    ]
