# Generated by Django 3.1.4 on 2021-04-16 21:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_auto_20210416_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='produce_orders',
            name='Deliver_Date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
