# Generated by Django 3.1.4 on 2021-04-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_produce_orders_deliver_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='produce_orders',
            name='Customer',
            field=models.CharField(default=0, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produce_orders',
            name='Customer_Email',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produce_orders',
            name='Deliver_To',
            field=models.CharField(default=0, max_length=45),
            preserve_default=False,
        ),
    ]
