# Generated by Django 3.1.4 on 2021-04-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_auto_20210416_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='produce_orders',
            name='Key',
            field=models.CharField(default=0, max_length=45),
            preserve_default=False,
        ),
    ]
