# Generated by Django 3.1.4 on 2021-04-18 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_produce_orders_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produce_orders',
            old_name='Key',
            new_name='Key_Value_Pair',
        ),
    ]
