# Generated by Django 3.1.4 on 2021-04-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0009_auto_20210417_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='rest1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nomenclature', models.CharField(max_length=25)),
                ('Qty', models.IntegerField(blank=True, null=True)),
                ('Unit', models.CharField(max_length=5)),
                ('Deliver', models.DateField()),
                ('PLU', models.IntegerField(blank=True, null=True)),
                ('Price', models.CharField(max_length=15)),
            ],
        ),
    ]
