# Generated by Django 3.1.4 on 2021-04-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_rest1'),
    ]

    operations = [
        migrations.AddField(
            model_name='rest1',
            name='Total',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
